# Generated by Django 2.1.3 on 2018-12-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='arg_b',
            field=models.IntegerField(),
        ),
    ]
